apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: oefeningen
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - image: vdatrainer/web
        name: web
