apiVersion: v1
kind: Pod
metadata:
  labels:
    run: stresser
  name: stresser
  namespace: oefeningen
spec:
  containers:
  - image: vish/stress
    name: stresser
    resources:
      limits:
        cpu: "0.5"
      requests:
        memory: "10G"
    args:
      - -cpus
      - "1"
      - -mem-total
      - "950Mi"
      - -mem-alloc-size
      - "100Mi"
      - -mem-alloc-sleep
      - "1s"
